train:
  dataset_path: GliomaSSL:split=TRAIN:root=/u/home/scholz/datasets/glioma_public_splits
  batch_size_per_gpu: 32
  num_workers: 15
  OFFICIAL_EPOCH_LENGTH: 83 # 2661 train samples / 32 batch size / 1 GPUs
  saveckp_freq: 10
student:
  arch: vit_base
  patch_size: 14
crops:
  global_crops_size: 518
  local_crops_size: 98
  global_crops_scale:
    - 0.5
    - 1.0
  local_crops_scale:
    - 0.2
    - 0.5
optim:
  base_lr: 1e-3
evaluation:
  eval_period_iterations: 1 # OFFICIAL_EPOCH_LENGTH * 10
  train_dataset_path: GliomaSupervised:split=TRAIN:root=/u/home/scholz/datasets/glioma_public_splits
  val_dataset_path: GliomaSupervised:split=VAL:root=/u/home/scholz/datasets/glioma_public_splits
  test_dataset_path: GliomaSupervised:split=TEST:root=/u/home/scholz/datasets/glioma_public_splits
  metric_types:
    - mcc
    - mean_per_class_accuracy
    - multiclass_auc
    - f1
